#!/usr/bin/env python3
"""
png2asm.py
Convert 10x8 B/W PNGs to assembly bytes (one byte per column).
Bit mapping: row 0 = top -> bit0 (LSB); row 7 = bottom -> bit7 (MSB).
Usage: python3 png2asm.py input_folder [output.asm]
Requires: Pillow (pip install pillow)
"""
import sys, os, re
from PIL import Image

def sanitize_label(name):
    name = re.sub(r'[^0-9A-Za-z_]', '_', name)
    if re.match(r'^[0-9]', name):
        name = '_' + name
    return name

def pixel_is_black(px):
    if isinstance(px, int):
        return px < 128
    if len(px) >= 3:
        r, g, b = px[0], px[1], px[2]
        lum = 0.299*r + 0.587*g + 0.114*b
        return lum < 128
    return False

def process_image(path):
    im = Image.open(path).convert('RGBA')
    w, h = im.size
    if (w, h) != (10, 8):
        raise ValueError(f"{os.path.basename(path)}: expected 10x8, got {w}x{h}")
    cols = []
    for x in range(w):
        val = 0
        for y in range(8):           # y=0 top ... y=7 bottom
            px = im.getpixel((x, y))
            if pixel_is_black(px):
                val |= (1 << y)     # bit y: 1<<0 -> top (LSB), 1<<7 -> bottom (MSB)
        cols.append(val)
    return cols

def format_byte(b):
    return f"0b{b:08b}"

def main(inp_folder, out_file):
    pngs = sorted(f for f in os.listdir(inp_folder) if f.lower().endswith('.png'))
    if not pngs:
        print("No PNG files found.")
        return
    with open(out_file, 'w', encoding='utf-8') as out:
        out.write("; Generated by png2asm.py\n\n")
        for fname in pngs:
            label = sanitize_label(os.path.splitext(fname)[0])
            out.write(";---------------------------------------\n")
            out.write(f"{label}:\n")
            cols = process_image(os.path.join(inp_folder, fname))
            for b in cols:
                out.write(f"\tdb {format_byte(b)}\n")
            out.write("\n")
    print(f"Wrote {len(pngs)} tiles to {out_file}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: png2asm.py input_folder [output.asm]")
        sys.exit(1)
    inp = sys.argv[1]
    outp = sys.argv[2] if len(sys.argv) > 2 else "tiles.asm"
    main(inp, outp)
